### ISSUE TITLE
Is the reconstruction of oversized scenes suitable?  I've scaled it up a lot, but it doesn't work very well.  Perhaps what should I try?  I did the same experiment with instant-NGP, with much better results.

### ISSUE THREAD

**Issue by 1zgh** [kwea123/ngp_pl#65] opened 2022-09-15 08:03 UTC
Is the reconstruction of oversized scenes suitable?  I've scaled it up a lot, but it doesn't work very well.  Perhaps what should I try?  I did the same experiment with instant-NGP, with much better results.
Python train.py --dataset_name nerf  --num_epochs  30 --scale 5.0  
I am looking forward too your reply.
Thanks!!

**Comment by kwea123** [comment] 2022-09-15 08:05
What data are you training? If you are training for original `nerf_blender`, `scale=0.5` (default) works.

**Comment by 1zgh** [comment] 2022-09-15 08:20
What I want to train is a model of the mountain. 
Scale =0.5 has a bad effect, so I adjust it to 5. But I don't clear the model for the mountain, is it still effective?  Or are there ways to try to improve?

**Comment by 1zgh** [comment] 2022-09-15 08:26
What I want to train is a model of the mountain.
Scale =0.5 has a bad effect, so I adjust it to 5. But I don't clear the model for the mountain, is it still effective? Or are there ways to try to improve?
The size of the photo is 4000 x 4000

**Comment by kwea123** [comment] 2022-09-15 08:30
If it's your own captured data, you should use colmap to estimate the pose and use `--dataset_name colmap` to train. Can you clarify more what your data is?

**Comment by 1zgh** [comment] 2022-09-15 08:58
Thanks！
Can you send the colmap command line instructions?
Data set I took the rockery photos by drone.

**Comment by kwea123** [comment] 2022-09-15 09:31
Please check out some colmap tutorial online, it is complicated to explain here. Also since it's not a bug here, I'll close the issue for now, feel free to reopen if it still doesn't work

**Closed by kwea123** 2022-09-15 09:31 UTC
